### ISSUE TITLE
Karma permissions system

### ISSUE THREAD

**Issue by bclindner** [bclindner/chipbot2#2]
It should be possible to disable upvoting and downvoting for certain cursed/blessed karma subjects, e.g. Other M and Chiptunes=WIN, respectively.
Configuration should be under a "blacklist" object in the karma config JSON, I think.
Maybe add an `isBlackListed` method to the KarmaManger object for this? Maybe `canUpvote` or `canDownvote`?

**Comment by ViridianForge** [comment]
It may be overfeatured - but I think having both canUpvote and canDownvote would capture the isBlackListed functionality.

Perhaps setting this for a given term could be restricted to folks with the mod flag?

**Comment by bclindner** [comment]
I'm mostly interested in implementing this as a way of handling the Other M ridicule system - we can disable upvoting on it, and then route people to a set of generics for both upvoting otherm and downvoting chiptune/chiptunes/chiptuneswin.

**Comment by bclindner** [comment]
Permissions system is in place - a simple `canUpvote` and `canDownvote` object - and is implemented in the karma voting system. Ridicule stuff is next up.

I may remake KarmaManager into a KarmaSubject class later on to better organize things.
