### ISSUE TITLE
Quote system (using lowdb)

### ISSUE THREAD

**Issue by bclindner** [bclindner/chipbot2#5]
Re-implementing the quote system shouldn't be too bad. Should probably have an interface object for adding/pulling quotes.

We can probably piggyback off of the karma database, likely using the same lowdb database file and connection, though keeping them seperate will probably have their advantages.

We probably want a QuoteManager class similar to how the KarmaManager manipulates the db, to keep things simple.

**Comment by ViridianForge** [comment]
Total agreement here.

**Comment by bclindner** [comment]
Beat you to it!
